### ISSUE TITLE
Titulinio puslapio apačia netelpa jei pavadinimas per ilgas

### ISSUE THREAD

**Issue by Alotar** [VirgisM/disertacijos-sablonas#1]
Jei disertacijos pavadinimas per ilgas ir užima dvi eilutes, apatinės titulinio puslapio eilutės persikelia į naują puslapį.

Galima ištaisyti [title/titlepage.tex](../tree/main/title/titlepage.tex) faile 29, 41, 133 ir 145 eilutėse `\vspace{50mm}` pakeitus į `\vspace{50mm minus 45mm}`.

**Comment by VirgisM** [comment]
Ačiū už pastabą ir pataisymą. Atnaujinimą įkėliau.
